jea/apps/base/urls.py
from django.urls import re_path
from jea.apps.base.views import IndexView

from jea.configs.settings import DEBUG

app_name = 'base'
urlpatterns = [
    re_path(r'^$', IndexView.as_view(), name='index'),
]

jea/apps/cadastro/urls.py
from django.urls import re_path

from jea.apps.cadastro.views.empresa import AdicionarEmpresaView,EmpresasListView, EditarEmpresaView
from jea.apps.cadastro.views.cliente import AdicionarClienteView, ClientesListView,EditarClienteView
from jea.apps.cadastro.views.produto import (AdicionarProdutoView, ProdutosListView, ProdutosBaixoEstoqueListView,
                                             EditarProdutoView, AdicionarCategoriaView, CategoriasListView, EditarCategoriaView, 
                                             AdicionarUnidadeView, UnidadesListView, EditarUnidadeView,
                                             AdicionarMarcaView, MarcasListView, EditarMarcaView)
from jea.apps.cadastro.views.ajax_views import InfoCliente, InfoEmpresa, InfoProduto

app_name = 'cadastro'
urlpatterns = [
    # Empresa
    # cadastro/empresa/adicionar/
    re_path(r'empresa/adicionar/$',
        AdicionarEmpresaView.as_view(), name='addempresaview'),
    # cadastro/empresa/listaempresas
    re_path(r'empresa/listaempresas/$',
        EmpresasListView.as_view(), name='listaempresasview'),
    # cadastro/empresa/editar/
    re_path(r'empresa/editar/(?P<pk>[0-9]+)/$',
        EditarEmpresaView.as_view(), name='editarempresaview'),

    # Cliente
    # cadastro/cliente/adicionar/
    re_path(r'cliente/adicionar/$',
        AdicionarClienteView.as_view(), name='addclienteview'),
    # cadastro/cliente/listaclientes
    re_path(r'cliente/listaclientes/$',
        ClientesListView.as_view(), name='listaclientesview'),
    # cadastro/cliente/editar/
    re_path(r'cliente/editar/(?P<pk>[0-9]+)/$',
        EditarClienteView.as_view(), name='editarclienteview'),

    # Produto
    # cadastro/produto/adicionar/
    re_path(r'produto/adicionar/$',
        AdicionarProdutoView.as_view(), name='addprodutoview'),
    # cadastro/produto/listaprodutos
    re_path(r'produto/listaprodutos/$',
        ProdutosListView.as_view(), name='listaprodutosview'),
    # cadastro/produto/listaprodutos/baixoestoque
    re_path(r'produto/listaprodutos/baixoestoque/$',
        ProdutosBaixoEstoqueListView.as_view(), name='listaprodutosbaixoestoqueview'),
    # cadastro/produto/editar/
    re_path(r'produto/editar/(?P<pk>[0-9]+)/$',
        EditarProdutoView.as_view(), name='editarprodutoview'),

    # Outros
    # Categorias
    # cadastro/outros/adicionarcategoria/
    re_path(r'outros/adicionarcategoria/$',
        AdicionarCategoriaView.as_view(), name='addcategoriaview'),
    # cadastro/outros/listacategorias/
    re_path(r'outros/listacategorias/$',
        CategoriasListView.as_view(), name='listacategoriasview'),
    # cadastro/outros/editarcategoria/
    re_path(r'outros/editarcategoria/(?P<pk>[0-9]+)/$',
        EditarCategoriaView.as_view(), name='editarcategoriaview'),

    # Unidades
    # cadastro/outros/adicionarunidade/
    re_path(r'outros/adicionarunidade/$',
        AdicionarUnidadeView.as_view(), name='addunidadeview'),
    # cadastro/outros/listaunidades/
    re_path(r'outros/listaunidades/$',
        UnidadesListView.as_view(), name='listaunidadesview'),
    # cadastro/outros/editarcunidade/
    re_path(r'outros/editarunidade/(?P<pk>[0-9]+)/$',
        EditarUnidadeView.as_view(), name='editarunidadeview'),

    # Marcas
    # cadastro/outros/adicionarmarca/
    re_path(r'outros/adicionarmarca/$',
        AdicionarMarcaView.as_view(), name='addmarcaview'),
    # cadastro/outros/listamarcas/
    re_path(r'outros/listamarcas/$',
        MarcasListView.as_view(), name='listamarcasview'),
    # cadastro/outros/editarmarca/
    re_path(r'outros/editarmarca/(?P<pk>[0-9]+)/$',
        EditarMarcaView.as_view(), name='editarmarcaview'),

    # Informacoes de dada empresa (Ajax request)
    re_path(r'infoempresa/$', InfoEmpresa.as_view(), name='infoempresa'),
    re_path(r'infocliente/$', InfoCliente.as_view(), name='infocliente'),
    re_path(r'infoproduto/$', InfoProduto.as_view(), name='infoproduto'),
]

jea/apps/login/urls.py
from django.urls import re_path
from jea.apps.login.views import *

app_name = 'login'
urlpatterns = [
    # login/
    re_path(r'^$', UserFormView.as_view(), name='loginview'),

    # login/registrar/
    re_path(r'registrar/$', UserRegistrationFormView.as_view(),
        name='registrarview'),

    # login/esqueceu/:
    re_path(r'^esqueceu/$', ForgotPasswordView.as_view(), name='esqueceuview'),

    # login/trocarsenha/:
    re_path(r'^trocarsenha/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$',
        PasswordResetConfirmView.as_view(), name='trocarsenhaview'),

    # logout
    re_path(r'^logout/$', UserLogoutView.as_view(), name='logoutview'),

    # login/perfil/
    re_path(r'^perfil/$', MeuPerfilView.as_view(), name='perfilview'),

    # login/editarperfil/
    re_path(r'^editarperfil/$', EditarPerfilView.as_view(), name='editarperfilview'),

    # login/usuarios/
    re_path(r'^usuarios/$', UsuariosListView.as_view(), name='usuariosview'),

    # login/usuarios/(id_usuario)
    re_path(r'usuarios/(?P<pk>[0-9]+)/$',
        UsuarioDetailView.as_view(), name='usuariodetailview'),

    # deletar usuario
    re_path(r'deletaruser/(?P<pk>[0-9]+)/$',
        DeletarUsuarioView.as_view(), name='deletarusuarioview'),

    # permissoes usuario
    re_path(r'permissoesusuario/(?P<pk>[0-9]+)/$',
        EditarPermissoesUsuarioView.as_view(), name='permissoesusuarioview'),

    # selecionar empresa
    re_path(r'selecionarempresa/$', SelecionarMinhaEmpresaView.as_view(),
        name='selecionarempresaview'),
]

jea/apps/vendas/urls.py
# -*- coding: utf-8 -*-

from django.urls import re_path

from jea.apps.vendas.views.vendas import (AdicionarPedidoVendaView, PedidoVendaListView, EditarPedidoVendaView,
                                          PedidoVendaAtrasadosListView, PedidoVendaEntregaHojeListView,
                                          GerarCopiaPedidoVendaView, GerarPDFPedidoVenda, CancelarPedidoVendaView, GerarPedidoVendaView, GerarPDFOrcamentoVenda) 
from jea.apps.vendas.views.pagamento import AdicionarCondicaoPagamentoView, CondicaoPagamentoListView, EditarCondicaoPagamentoView, InfoCondicaoPagamento
from jea.apps.vendas.views.ajax_views import InfoVenda


app_name = 'vendas'
urlpatterns = [
    # Pedidos de venda
    # vendas/pedidovenda/adicionar/
    re_path(r'pedidovenda/adicionar/$',
        AdicionarPedidoVendaView.as_view(), name='addpedidovendaview'),
    # vendas/pedidovenda/listapedidovenda
    re_path(r'pedidovenda/listapedidovenda/$',
        PedidoVendaListView.as_view(), name='listapedidovendaview'),
    # vendas/pedidovenda/editar/
    re_path(r'pedidovenda/editar/(?P<pk>[0-9]+)/$',
        EditarPedidoVendaView.as_view(), name='editarpedidovendaview'),
    # vendas/pedidovenda/listapedidovenda/atrasados
    re_path(r'pedidovenda/listapedidovenda/atrasados/$',
        PedidoVendaAtrasadosListView.as_view(), name='listapedidovendaatrasadosview'),
    # vendas/pedidovenda/listapedidovenda/hoje
    re_path(r'pedidovenda/listapedidovenda/hoje/$',
        PedidoVendaEntregaHojeListView.as_view(), name='listapedidovendahojeview'),

    # Condicao pagamento
    # vendas/pagamento/adicionar/
    re_path(r'pagamento/adicionar/$', AdicionarCondicaoPagamentoView.as_view(),
        name='addcondicaopagamentoview'),
    # vendas/pagamento/listacondicaopagamento
    re_path(r'pagamento/listacondicaopagamento/$',
        CondicaoPagamentoListView.as_view(), name='listacondicaopagamentoview'),
    # vendas/pagamento/editar/
    re_path(r'pagamento/editar/(?P<pk>[0-9]+)/$', EditarCondicaoPagamentoView.as_view(
    ), name='editarcondicaopagamentoview'),

    # Request ajax views
    re_path(r'infocondpagamento/$', InfoCondicaoPagamento.as_view(),
        name='infocondpagamento'),
    re_path(r'infovenda/$', InfoVenda.as_view(), name='infovenda'),

    # Gerar pdf pedido
    re_path(r'gerarpdfpedidovenda/(?P<pk>[0-9]+)/$',
        GerarPDFPedidoVenda.as_view(), name='gerarpdfpedidovenda'),
    # Gerar pedido a partir de um orçamento
    re_path(r'gerarpedidovenda/(?P<pk>[0-9]+)/$',
        GerarPedidoVendaView.as_view(), name='gerarpedidovenda'),
    # Copiar orcamento cancelado ou baixado
    # Copiar pedido cancelado ou baixado
    re_path(r'copiarpedidovenda/(?P<pk>[0-9]+)/$',
        GerarCopiaPedidoVendaView.as_view(), name='copiarpedidovenda'),
    # Cancelar Pedido de venda
    re_path(r'cancelarpedidovenda/(?P<pk>[0-9]+)/$',
        CancelarPedidoVendaView.as_view(), name='cancelarpedidovenda'),]

jea/urls.py
# -*- coding: utf-8 -*-

from django.urls import include, re_path
from django.contrib import admin
from django.conf.urls.static import static
from .configs.settings import DEBUG, MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('jea.apps.base.urls')),
    re_path(r'^login/', include('jea.apps.login.urls')),
    re_path(r'^cadastro/', include('jea.apps.cadastro.urls')),
    re_path(r'^vendas/', include('jea.apps.vendas.urls')),
    re_path(r'^estoque/', include('jea.apps.estoque.urls')),
]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

jea/apps/base/models.py
from django.db import models

# Create your models here.

jea/apps/cadastro/models/cliente.py
# -*- coding: utf-8 -*-

from django.db import models

from decimal import Decimal

from jea.apps.cadastro.models.base import Pessoa


class Cliente(Pessoa):
    limite_de_credito = models.DecimalField(
        max_digits=15, decimal_places=2, default=Decimal('0.00'), null=True, blank=True)
    id_estrangeiro = models.CharField(max_length=20, null=True, blank=True)

    class Meta:
        verbose_name = "Cliente"

jea/apps/cadastro/forms/cliente.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import gettext_lazy as _

from jea.apps.cadastro.models.cliente import Cliente


class ClienteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ClienteForm, self).__init__(*args, **kwargs)
        self.fields['limite_de_credito'].localize = True

    class Meta:
        model = Cliente
        fields = ('nome_razao_social', 'tipo_pessoa', 'inscricao_municipal',
                  'limite_de_credito', 'id_estrangeiro', 'informacoes_adicionais', )
        widgets = {
            'nome_razao_social': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_pessoa': forms.RadioSelect(attrs={'class': 'form-control'}),
            'limite_de_credito': forms.TextInput(attrs={'class': 'form-control decimal-mask'}),
            'informacoes_adicionais': forms.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {
            'nome_razao_social': _('Razão Social'),
            'tipo_pessoa': _(''),
            'limite_de_credito': _('Limite de Crédito'),
            'informacoes_adicionais': _('Informações Adicionais'),
        }

    def save(self, commit=True):
        instance = super(ClienteForm, self).save(commit=False)
        instance.criado_por = self.request.user
        if commit:
            instance.save()
        return 

jea/apps/cadastro/forms/empresa.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import gettext_lazy as _

from jea.apps.cadastro.models.empresa import Empresa, MinhaEmpresa


class EmpresaForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(EmpresaForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Empresa
        fields = ('nome_razao_social', 'inscricao_municipal', 'cnae',
                  'logo_file', 'informacoes_adicionais',)

        widgets = {
            'nome_razao_social': forms.TextInput(attrs={'class': 'form-control'}),
            'cnae': forms.TextInput(attrs={'class': 'form-control'}),
            'inscricao_municipal': forms.TextInput(attrs={'class': 'form-control'}),
            'logo_file': forms.FileInput(attrs={'class': 'form-control', 'accept': 'image/*'}),
            'informacoes_adicionais': forms.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {
            'nome_razao_social': _('Razão Social'),
            'cnae': _('CNAE'),
            'inscricao_municipal': _('Inscrição Municipal'),
            'logo_file': _('Logo'),
            'informacoes_adicionais': _('Informações Adicionais'),
        }

    def save(self, commit=True):
        instance = super(EmpresaForm, self).save(commit=False)
        instance.tipo_pessoa = 'PJ'
        instance.criado_por = self.request.user
        if 'empresa_form-logo_file' in self.request.FILES:
            instance.logo_file = self.request.FILES['empresa_form-logo_file']
        if commit:
            instance.save()
        return instance


class MinhaEmpresaForm(forms.ModelForm):

    class Meta:
        model = MinhaEmpresa
        fields = ('m_empresa',)

        widgets = {
            'm_empresa': forms.Select(attrs={'class': 'form-control'}),
        }
        labels = {
            'm_empresa': _('Minha Empresa'),
        }

jea/apps/cadastro/forms/inline_formsets.py
# -*- coding: utf-8 -*-

from django import forms
from django.forms import inlineformset_factory
from django.utils.translation import gettext_lazy as _

from jea.apps.cadastro.models.base import Pessoa, Endereco, Telefone, Email, Site, Documento


class EnderecoForm(forms.ModelForm):

    class Meta:
        model = Endereco
        fields = ('tipo_endereco', 'logradouro', 'numero', 'bairro',
                  'complemento', 'pais', 'uf', 'cep', 'municipio',)

        labels = {
            'tipo_endereco': _('Tipo'),
            'logradouro': _("Logradouro"),
            'numero': _("Número"),
            'bairro': _("Bairro"),
            'complemento': _("Complemento"),
            'pais': _("País"),
            'municipio': _("Município (sem acentuação)"),
            'cep': _("CEP (Apenas dígitos)"),
            'uf': _("UF"),
        }
        widgets = {
            'tipo_endereco': forms.Select(attrs={'class': 'form-control'}),
            'logradouro': forms.TextInput(attrs={'class': 'form-control'}),
            'numero': forms.TextInput(attrs={'class': 'form-control'}),
            'bairro': forms.TextInput(attrs={'class': 'form-control'}),
            'complemento': forms.TextInput(attrs={'class': 'form-control'}),
            'pais': forms.TextInput(attrs={'class': 'form-control'}),
            'municipio': forms.Select(attrs={'class': 'form-control'}),
            'cep': forms.TextInput(attrs={'class': 'form-control'}),
            'uf': forms.Select(attrs={'class': 'form-control'}),
        }


class TelefoneForm(forms.ModelForm):

    class Meta:
        model = Telefone
        fields = ('tipo_telefone', 'telefone',)
        labels = {
            'tipo_telefone': _("Telefone"),
            'telefone': _(''),
        }
        widgets = {
            'tipo_telefone': forms.Select(attrs={'class': 'form-control'}),
            'telefone': forms.TextInput(attrs={'class': 'form-control'}),
        }


class EmailForm(forms.ModelForm):

    class Meta:
        model = Email
        fields = ('email',)
        labels = {
            'email': _('Email')
        }
        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }


class SiteForm(forms.ModelForm):

    class Meta:
        model = Site
        fields = ('site',)
        labels = {
            'site': _('Site'),
        }
        widgets = {
            'site': forms.TextInput(attrs={'class': 'form-control'}),
        }


class DocumentoForm(forms.ModelForm):

    class Meta:
        model = Documento
        fields = ('tipo', 'documento',)
        labels = {
            'tipo': _('Tipo'),
            'documento': _('Documento'),
        }
        widgets = {
            'tipo': forms.TextInput(attrs={'class': 'form-control'}),
            'documento': forms.TextInput(attrs={'class': 'form-control'}),
        }


EnderecoFormSet = inlineformset_factory(
    Pessoa, Endereco, form=EnderecoForm, extra=1, can_delete=True)
TelefoneFormSet = inlineformset_factory(
    Pessoa, Telefone, form=TelefoneForm, extra=1, can_delete=True)
EmailFormSet = inlineformset_factory(
    Pessoa, Email, form=EmailForm, extra=1, can_delete=True)
SiteFormSet = inlineformset_factory(
    Pessoa, Site, form=SiteForm, extra=1, can_delete=True)
DocumentoFormSet = inlineformset_factory(
    Pessoa, Documento, form=DocumentoForm, extra=1, can_delete=True)

jea/apps/estoque/forms/local.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import gettext_lazy as _

from jea.apps.estoque.models.local import LocalEstoque


class LocalEstoqueForm(forms.ModelForm):

    class Meta:
        model = LocalEstoque
        fields = ('descricao',)
        widgets = {
            'descricao': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'descricao': _('Descrição'),
        }

jea/templates/login/detalhe_users.html
{%extends 'base/base.html'%}

{%block title%}Sobre usuário{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid block">
    
    {% include 'base/msg_sucesso.html' %}

    <div class="block-header">
      <h2>USUÁRIO</h2>
    </div>
    <div class="block-content">
      <div class="card">
        <div class="header">
          <h2>
            <a href="{%url 'login:usuariosview'%}"><i class="material-icons">&#xE5C4;</i></a>
            <span><b>Usuário: </b>{{user_match.username}}{% if user_match.is_superuser %} (Admin){% endif %}</span>
          </h2>
          <div class="header-btn">
            {%if not user_match.is_superuser%} 
            <form action="{% url 'login:deletarusuarioview' user_match.id %}" method="post">
              {% csrf_token %}
              <input type="hidden" name="user_id" value="{{user_match.id}}">
              <button class="btn btn-red" type="submit"><i class="material-icons">&#xE872;</i><span> REMOVER</span></button>
            </form>
            {%endif%}
          </div>
        </div>
        <div class="body perfil-user">
            <div class="col-md-3 foto-perfil">  
              {% if user_foto %}
              <img src="/media/{{user_foto}}"/>
              {%else%}
              <img src="/media/imagens/user.png"/>
              {%endif%}
            </div>
            <div class="col-md-8">
              <table class="table">
                <tbody>
                  <tr>
                    <td>Status:</td>
                    <td>{% if user_match.is_superuser %}Administrador{%else%}Usuário{%endif%}</td>
                  </tr>
                  <tr>
                    <td>Nome:</td>
                    <td>{{user_match.first_name}}</td>
                  </tr>
                  <tr>
                    <td>Sobrenome:</td>
                    <td>{{user_match.last_name}}</td>
                  </tr>
                  <tr>
                    <td>Nome de usuário:</td>
                    <td>{{user_match.username}}</td>
                  </tr>
                  <tr>
                    <td>Email:</td>
                    <td>{{user_match.email}}</td>
                  </tr>

                </tbody>
              </table>

            </div>
            <a href="{% url 'login:permissoesusuarioview' user_match.id %}" style="margin:15px;float:right;" class="btn btn-primary">EDITAR PERMISSÕES</a>
        </div>
      </div>
    </div>

    
  </div>
</section>


{%endblock%}

jea/templates/login/editar_perfil.html
{%extends 'base/base.html'%}

{%block title%}Editar Perfil{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid block">
    <div class="block-header">
      <h2>PERFIL</h2>
    </div>
      
    {% include 'base/form_error_alert.html' %}

    <div class="block-content">
      <div class="card">
        <div class="header">
          <h2>
            <a href="{% url 'login:perfilview' %}"><i class="material-icons">&#xE5C4;</i></a>
            EDITAR PERFIL
          </h2>
        </div>

        <div class="body">
          <form role="form" action="" method="post" enctype="multipart/form-data" >
           {% csrf_token %}
           
           {% for field in form %}

           <div class="form-group">
            <div class="form-line">
              <label>{{field.label}}</label>
              {{field}}
            </div>
          </div>
          
          {% endfor %}

          <div class="form-group">
            <label>{{minha_empresa_form.m_empresa.label}}</label>
            <div class="input-group">
              <div class="form-line">
                {{minha_empresa_form.m_empresa}}
              </div>
              <a class="input-group-addon" style="color: green;" href="{% url 'cadastro:addempresaview' %}"><i class="material-icons add-new-icon" title="Adicionar empresa">&#xE147;</i></a>
            </div>
          </div>

          <button class="btn btn-success foot-btn" style="margin-right:0px;" type="submit"><i class="material-icons">&#xE3C9;</i><span> ALTERAR</span></button>
        </form>
        
      </div>

    </div>
  </div>
  
</div>
</section>


{%endblock%}

jea/templates/login/esqueceu_senha.html
{%extends 'base/base.html'%}


{%block title%}Trocar senha{%endblock%}
{%block side_top_bars%}{%endblock%}

{%block body_class%}login-page ls-closed{%endblock%}

{%block content%}
<div class="login-box">

    {% include 'login/logo.html' %}
    
    <div class="card">
        <div class="body">
            <form method="POST">
                <div class="msg">Escreva o endereço de email ou nome de usuário registrado. Um email será enviado contendo o link para a troca de senha.
                
                {% include 'base/form_error_msg.html' %}

                </div>
                
                {% csrf_token %}
                
                <div class="input-group">
                    <div class="form-line">
                        {{form.email_or_username}}
                    </div>
                </div>

                <div style="text-align:center;">
                    <button class="btn btn-red" type="submit">ENVIAR</button>
                </div>
            </form>
            <div class="msg" style="margin-top:40px;margin-bottom:15px;">
                <a href="{% url 'login:loginview'%}">Voltar</a>
            </div>
          
        </div>
    </div>
</div>

{%endblock%}

jea/templates/login/lista_users.html
{%extends 'base/base.html'%}

{%block title%}Usuários{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid lista">
    <div class="lista-header">
      <h2>USUÁRIOS</h2>
    </div>
    
    {% include 'base/msg_sucesso.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lista-content">
      <div class="card">
        <form action="" method="post">
          {% csrf_token %}
          <div class="header">
            <h2>
              USUÁRIOS CADASTRADOS
            </h2>
              <div class="header-btn">
                <a href="{% url 'login:registrarview' %}" class="btn btn-success"><i class="material-icons">&#xE7FE;</i><span> CRIAR NOVO</span></a>
                <button class="btn btn-red btn-remove"><i class="material-icons">&#xE872;</i></button>
              </div>
          </div>

          <div class="body">

           {% include 'base/search.html' %}

           <div class="table-responsive">
            <table id="lista-database" class="table table-bordered table-striped lista-table">
              <thead>
                <tr>
                  <th>#ID</th>                   
                  <th>Nome de usuário</th>
                  <th>Nome</th>
                  <th>Sobrenome</th>
                  <th>Status</th>
                  <th>Remover</th>
                </tr>
              </thead>

              <tbody>
               {% if all_users%}
               {% for usr in all_users %}
               <tr class="clickable-row" data-href="{% url 'login:usuariodetailview' usr.id %}">
                <td>{{usr.id}}</td>
                <td>{{usr.username}}</td>
                <td>{{usr.first_name|default_if_none:""}}</td>
                <td>{{usr.last_name|default_if_none:""}}</td>
                <td>{%if usr.is_superuser%}Administrador{%else%}Usuário{%endif%}</td>
                <td class="lista-remove">
                  {%if not usr.is_superuser%}
                  <input type="checkbox" name="{{usr.id}}" id="remover-entrada-{{usr.id}}"/>
                  <label class="remove-entry-label" for="remover-entrada-{{usr.id}}"></label>
                  {%endif%}
                </td>
              </tr>
              {% endfor %}
              {%else%}
              {%endif%}
            </tbody>
          </table>
        </div>

      </div>

    </form>

    {% include 'base/modal.html' %}

  </div>
</div>

</div>
</section>


{%endblock%}

jea/templates/login/login.html
{%extends 'base/base.html'%}


{%block title%}Login{%endblock%}
{%block side_top_bars%}{%endblock%}

{%block body_class%}login-page ls-closed{%endblock%}

{%block content%}
<div class="login-box">

    {% include 'login/logo.html' %}

    <div class="card">
        <div class="body">
        	{% if not request.user.is_authenticated %}
            <form id="login" method="POST">
            	{% csrf_token %}
                <div class="msg">Digite seu nome de usuário e a senha para entrar

                {% include 'base/form_error_msg.html' %}

                </div>

                {% for field in form %}
                <div class="input-group">
                    <span class="input-group-addon">
                        <i class="material-icons">{{field.label}}</i>
                    </span>
                    <div class="form-line">
                        {{field}}
                    </div>
                </div>
                {% endfor %}

                <div class="row">
                    <div class="col-xs-8">
                        <input type="checkbox" name="remember_me" id="remember_me" class="filled-in chk-col-light-blue">
                        <label for="remember_me">Lembrar</label>
                    </div>
                    <div class="col-xs-4">
                        <button class="btn btn-block btn-red" type="submit">ENTRAR</button>
                    </div>
                </div>

                <div class="msg" style="margin-top:20px;">
                    <a href="{% url 'login:esqueceuview' %}">Esqueceu a senha?</a><br/>
                </div>

            </form>
            {%endif%}

            {% include 'base/modal.html' %}

        </div>
    </div>
</div>
{%endblock%}


{% block js %}

    <!-- Mensagem caso sucesso ao solicitar troca de senha -->
    {% if messages %}

    {%for message in messages%}
    {% if 'success' in message.tags %}

    <script type="text/javascript">
        $.Admin.messages.msgSucesso("{{message}}");
    </script>
    {%endif%}
    {%endfor%}

    {% endif %}

{% endblock %}

jea/templates/login/logo.html
<div class="logo">
    <a href="javascript:void(0);" class="text-logo">J&A<b style="color:#e76d64;">Holding</b></a>
    <small>Sistema de gerenciamento de vendas</small>
</div>

jea/templates/login/trocar_senha_email.html
Mensagem de recuperação de senha. Esta mensagem foi enviada pois ocorreu uma solicitação de troca de senha em seu DjangoSIGE.
Abra o link abaixo e defina uma nova senha:
{{protocol}}{{domain}}{% url 'login:trocarsenhaview' uidb64=uid token=token %}

Seu nome de usuário é: {{user}}