jea/apps/base/urls.py
from django.urls import re_path
from jea.apps.base.views import IndexView

from jea.configs.settings import DEBUG

app_name = 'base'
urlpatterns = [
    re_path(r'^$', IndexView.as_view(), name='index'),
]

jea/apps/cadastro/urls.py
from django.urls import re_path

from jea.apps.cadastro.views.empresa import AdicionarEmpresaView,EmpresasListView, EditarEmpresaView
from jea.apps.cadastro.views.cliente import AdicionarClienteView, ClientesListView,EditarClienteView
from jea.apps.cadastro.views.produto import (AdicionarProdutoView, ProdutosListView, ProdutosBaixoEstoqueListView,
                                             EditarProdutoView, AdicionarCategoriaView, CategoriasListView, EditarCategoriaView, 
                                             AdicionarUnidadeView, UnidadesListView, EditarUnidadeView,
                                             AdicionarMarcaView, MarcasListView, EditarMarcaView)
from jea.apps.cadastro.views.ajax_views import InfoCliente, InfoEmpresa, InfoProduto

app_name = 'cadastro'
urlpatterns = [
    # Empresa
    # cadastro/empresa/adicionar/
    re_path(r'empresa/adicionar/$',
        AdicionarEmpresaView.as_view(), name='addempresaview'),
    # cadastro/empresa/listaempresas
    re_path(r'empresa/listaempresas/$',
        EmpresasListView.as_view(), name='listaempresasview'),
    # cadastro/empresa/editar/
    re_path(r'empresa/editar/(?P<pk>[0-9]+)/$',
        EditarEmpresaView.as_view(), name='editarempresaview'),

    # Cliente
    # cadastro/cliente/adicionar/
    re_path(r'cliente/adicionar/$',
        AdicionarClienteView.as_view(), name='addclienteview'),
    # cadastro/cliente/listaclientes
    re_path(r'cliente/listaclientes/$',
        ClientesListView.as_view(), name='listaclientesview'),
    # cadastro/cliente/editar/
    re_path(r'cliente/editar/(?P<pk>[0-9]+)/$',
        EditarClienteView.as_view(), name='editarclienteview'),

    # Produto
    # cadastro/produto/adicionar/
    re_path(r'produto/adicionar/$',
        AdicionarProdutoView.as_view(), name='addprodutoview'),
    # cadastro/produto/listaprodutos
    re_path(r'produto/listaprodutos/$',
        ProdutosListView.as_view(), name='listaprodutosview'),
    # cadastro/produto/listaprodutos/baixoestoque
    re_path(r'produto/listaprodutos/baixoestoque/$',
        ProdutosBaixoEstoqueListView.as_view(), name='listaprodutosbaixoestoqueview'),
    # cadastro/produto/editar/
    re_path(r'produto/editar/(?P<pk>[0-9]+)/$',
        EditarProdutoView.as_view(), name='editarprodutoview'),

    # Outros
    # Categorias
    # cadastro/outros/adicionarcategoria/
    re_path(r'outros/adicionarcategoria/$',
        AdicionarCategoriaView.as_view(), name='addcategoriaview'),
    # cadastro/outros/listacategorias/
    re_path(r'outros/listacategorias/$',
        CategoriasListView.as_view(), name='listacategoriasview'),
    # cadastro/outros/editarcategoria/
    re_path(r'outros/editarcategoria/(?P<pk>[0-9]+)/$',
        EditarCategoriaView.as_view(), name='editarcategoriaview'),

    # Unidades
    # cadastro/outros/adicionarunidade/
    re_path(r'outros/adicionarunidade/$',
        AdicionarUnidadeView.as_view(), name='addunidadeview'),
    # cadastro/outros/listaunidades/
    re_path(r'outros/listaunidades/$',
        UnidadesListView.as_view(), name='listaunidadesview'),
    # cadastro/outros/editarcunidade/
    re_path(r'outros/editarunidade/(?P<pk>[0-9]+)/$',
        EditarUnidadeView.as_view(), name='editarunidadeview'),

    # Marcas
    # cadastro/outros/adicionarmarca/
    re_path(r'outros/adicionarmarca/$',
        AdicionarMarcaView.as_view(), name='addmarcaview'),
    # cadastro/outros/listamarcas/
    re_path(r'outros/listamarcas/$',
        MarcasListView.as_view(), name='listamarcasview'),
    # cadastro/outros/editarmarca/
    re_path(r'outros/editarmarca/(?P<pk>[0-9]+)/$',
        EditarMarcaView.as_view(), name='editarmarcaview'),

    # Informacoes de dada empresa (Ajax request)
    re_path(r'infoempresa/$', InfoEmpresa.as_view(), name='infoempresa'),
    re_path(r'infocliente/$', InfoCliente.as_view(), name='infocliente'),
    re_path(r'infoproduto/$', InfoProduto.as_view(), name='infoproduto'),
]

jea/apps/estoque/urls.py
# -*- coding: utf-8 -*-

from django.urls import re_path

from jea.apps.estoque.views.consulta import ConsultaEstoqueView
from jea.apps.estoque.views.local import AdicionarLocalEstoqueView,LocalEstoqueListView, EditarLocalEstoqueView
from jea.apps.estoque.views.movimento import (MovimentoEstoqueListView, AdicionarEntradaEstoqueView, EntradaEstoqueListView, DetalharEntradaEstoqueView, 
                                              AdicionarSaidaEstoqueView, SaidaEstoqueListView, AdicionarTransferenciaEstoqueView, DetalharSaidaEstoqueView,
                                              TransferenciaEstoqueListView, DetalharTransferenciaEstoqueView)


app_name = 'estoque'
urlpatterns = [
    # Consulta de estoque
    # estoque/consultaestoque/
    re_path(r'consultaestoque/$', ConsultaEstoqueView.as_view(),
        name='consultaestoqueview'),

    # Local de estoque
    # estoque/local/adicionar/
    re_path(r'local/saida/adicionar/$',
        AdicionarLocalEstoqueView.as_view(), name='addlocalview'),
    # estoque/local/listalocal
    re_path(r'local/listalocal/$', LocalEstoqueListView.as_view(),
        name='listalocalview'),
    # estoque/local/editar/
    re_path(r'local/editar/(?P<pk>[0-9]+)/$',
        EditarLocalEstoqueView.as_view(), name='editarlocalview'),

    # Movimento de estoque
    # Lista todos movimentos
    re_path(r'movimentos/$', MovimentoEstoqueListView.as_view(),
        name='listamovimentoestoqueview'),

    # EntradaEstoque
    # estoque/movimento/adicionarentrada/
    re_path(r'movimento/adicionarentrada/$',
        AdicionarEntradaEstoqueView.as_view(), name='addentradaestoqueview'),
    # estoque/movimento/listaentradas/
    re_path(r'movimento/listaentradas/$', EntradaEstoqueListView.as_view(),
        name='listaentradasestoqueview'),
    # estoque/movimento/editarentrada/
    re_path(r'movimento/editarentrada/(?P<pk>[0-9]+)/$', DetalharEntradaEstoqueView.as_view(
    ), name='detalharentradaestoqueview'),

    # SaidaEstoque
    # estoque/movimento/adicionarsaida/
    re_path(r'movimento/adicionarsaida/$',
        AdicionarSaidaEstoqueView.as_view(), name='addsaidaestoqueview'),
    # estoque/movimento/listasaidas/
    re_path(r'movimento/listasaidas/$', SaidaEstoqueListView.as_view(),
        name='listasaidasestoqueview'),
    # estoque/movimento/editarsaida/
    re_path(r'movimento/editarsaida/(?P<pk>[0-9]+)/$',
        DetalharSaidaEstoqueView.as_view(), name='detalharsaidaestoqueview'),

    # TransferenciaEstoque
    # estoque/movimento/adicionartransferencia/
    re_path(r'movimento/adicionartransferencia/$',
        AdicionarTransferenciaEstoqueView.as_view(), name='addtransferenciaestoqueview'),
    # estoque/movimento/listatransferencias/
    re_path(r'movimento/listatransferencias/$', TransferenciaEstoqueListView.as_view(),
        name='listatransferenciasestoqueview'),
    # estoque/movimento/editartransferencia/
    re_path(r'movimento/editartransferencia/(?P<pk>[0-9]+)/$', DetalharTransferenciaEstoqueView.as_view(
    ), name='detalhartransferenciaestoqueview'),
]

jea/apps/login/urls.py
from django.urls import re_path
from jea.apps.login.views import *

app_name = 'login'
urlpatterns = [
    # login/
    re_path(r'^$', UserFormView.as_view(), name='loginview'),

    # login/registrar/
    re_path(r'registrar/$', UserRegistrationFormView.as_view(),
        name='registrarview'),

    # login/esqueceu/:
    re_path(r'^esqueceu/$', ForgotPasswordView.as_view(), name='esqueceuview'),

    # login/trocarsenha/:
    re_path(r'^trocarsenha/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$',
        PasswordResetConfirmView.as_view(), name='trocarsenhaview'),

    # logout
    re_path(r'^logout/$', UserLogoutView.as_view(), name='logoutview'),

    # login/perfil/
    re_path(r'^perfil/$', MeuPerfilView.as_view(), name='perfilview'),

    # login/editarperfil/
    re_path(r'^editarperfil/$', EditarPerfilView.as_view(), name='editarperfilview'),

    # login/usuarios/
    re_path(r'^usuarios/$', UsuariosListView.as_view(), name='usuariosview'),

    # login/usuarios/(id_usuario)
    re_path(r'usuarios/(?P<pk>[0-9]+)/$',
        UsuarioDetailView.as_view(), name='usuariodetailview'),

    # deletar usuario
    re_path(r'deletaruser/(?P<pk>[0-9]+)/$',
        DeletarUsuarioView.as_view(), name='deletarusuarioview'),

    # permissoes usuario
    re_path(r'permissoesusuario/(?P<pk>[0-9]+)/$',
        EditarPermissoesUsuarioView.as_view(), name='permissoesusuarioview'),

    # selecionar empresa
    re_path(r'selecionarempresa/$', SelecionarMinhaEmpresaView.as_view(),
        name='selecionarempresaview'),
]

jea/apps/vendas/urls.py
# -*- coding: utf-8 -*-

from django.urls import re_path

from jea.apps.vendas.views.vendas import (AdicionarPedidoVendaView, PedidoVendaListView, EditarPedidoVendaView,
                                          PedidoVendaAtrasadosListView, PedidoVendaEntregaHojeListView,
                                          GerarCopiaPedidoVendaView, GerarPDFPedidoVenda, CancelarPedidoVendaView, GerarPedidoVendaView, GerarPDFOrcamentoVenda) 
from jea.apps.vendas.views.pagamento import AdicionarCondicaoPagamentoView, CondicaoPagamentoListView, EditarCondicaoPagamentoView, InfoCondicaoPagamento
from jea.apps.vendas.views.ajax_views import InfoVenda


app_name = 'vendas'
urlpatterns = [
    # Pedidos de venda
    # vendas/pedidovenda/adicionar/
    re_path(r'pedidovenda/adicionar/$',
        AdicionarPedidoVendaView.as_view(), name='addpedidovendaview'),
    # vendas/pedidovenda/listapedidovenda
    re_path(r'pedidovenda/listapedidovenda/$',
        PedidoVendaListView.as_view(), name='listapedidovendaview'),
    # vendas/pedidovenda/editar/
    re_path(r'pedidovenda/editar/(?P<pk>[0-9]+)/$',
        EditarPedidoVendaView.as_view(), name='editarpedidovendaview'),
    # vendas/pedidovenda/listapedidovenda/atrasados
    re_path(r'pedidovenda/listapedidovenda/atrasados/$',
        PedidoVendaAtrasadosListView.as_view(), name='listapedidovendaatrasadosview'),
    # vendas/pedidovenda/listapedidovenda/hoje
    re_path(r'pedidovenda/listapedidovenda/hoje/$',
        PedidoVendaEntregaHojeListView.as_view(), name='listapedidovendahojeview'),

    # Condicao pagamento
    # vendas/pagamento/adicionar/
    re_path(r'pagamento/adicionar/$', AdicionarCondicaoPagamentoView.as_view(),
        name='addcondicaopagamentoview'),
    # vendas/pagamento/listacondicaopagamento
    re_path(r'pagamento/listacondicaopagamento/$',
        CondicaoPagamentoListView.as_view(), name='listacondicaopagamentoview'),
    # vendas/pagamento/editar/
    re_path(r'pagamento/editar/(?P<pk>[0-9]+)/$', EditarCondicaoPagamentoView.as_view(
    ), name='editarcondicaopagamentoview'),

    # Request ajax views
    re_path(r'infocondpagamento/$', InfoCondicaoPagamento.as_view(),
        name='infocondpagamento'),
    re_path(r'infovenda/$', InfoVenda.as_view(), name='infovenda'),

    # Gerar pdf pedido
    re_path(r'gerarpdfpedidovenda/(?P<pk>[0-9]+)/$',
        GerarPDFPedidoVenda.as_view(), name='gerarpdfpedidovenda'),
    # Gerar pedido a partir de um orçamento
    re_path(r'gerarpedidovenda/(?P<pk>[0-9]+)/$',
        GerarPedidoVendaView.as_view(), name='gerarpedidovenda'),
    # Copiar orcamento cancelado ou baixado
    # Copiar pedido cancelado ou baixado
    re_path(r'copiarpedidovenda/(?P<pk>[0-9]+)/$',
        GerarCopiaPedidoVendaView.as_view(), name='copiarpedidovenda'),
    # Cancelar Pedido de venda
    re_path(r'cancelarpedidovenda/(?P<pk>[0-9]+)/$',
        CancelarPedidoVendaView.as_view(), name='cancelarpedidovenda'),]

jea/urls.py
# -*- coding: utf-8 -*-

from django.urls import include, re_path
from django.contrib import admin
from django.conf.urls.static import static
from .configs.settings import DEBUG, MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('jea.apps.base.urls')),
    re_path(r'^login/', include('jea.apps.login.urls')),
    re_path(r'^cadastro/', include('jea.apps.cadastro.urls')),
    re_path(r'^vendas/', include('jea.apps.vendas.urls')),
    re_path(r'^estoque/', include('jea.apps.estoque.urls')),
]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

jea/apps/base/models.py
from django.db import models

# Create your models here.

jea/apps/cadastro/models/produto.py
# -*- coding: utf-8 -*-

from django.db import models
from django.core.validators import MinValueValidator
from decimal import Decimal


TP_OPERACAO_OPCOES = (
    (u'0', u'0 - Entrada'),
    (u'1', u'1 - Saída'),
)

ID_DEST_OPCOES = (
    (u'1', u'1 - Operação interna.'),
    (u'2', u'2 - Operação interestadual.'),
    (u'3', u'3 - Operação com exterior'),
)


class Categoria(models.Model):
    categoria_desc = models.CharField(max_length=32)

    class Meta:
        verbose_name = "Categoria"

    def __unicode__(self):
        s = u'%s' % (self.categoria_desc)
        return s

    def __str__(self):
        s = u'%s' % (self.categoria_desc)
        return s


class Marca(models.Model):
    marca_desc = models.CharField(max_length=32)

    class Meta:
        verbose_name = "Marca"

    def __unicode__(self):
        s = u'%s' % (self.marca_desc)
        return s

    def __str__(self):
        s = u'%s' % (self.marca_desc)
        return s


class Unidade(models.Model):
    sigla_unidade = models.CharField(max_length=3)
    unidade_desc = models.CharField(max_length=16)

    class Meta:
        verbose_name = "Unidade"

    def __unicode__(self):
        s = u'(%s) %s' % (self.sigla_unidade, self.unidade_desc)
        return s

    def __str__(self):
        s = u'(%s) %s' % (self.sigla_unidade, self.unidade_desc)
        return s


class Produto(models.Model):
    # Dados gerais
    codigo = models.CharField(max_length=15)
    codigo_barras = models.CharField(
        max_length=16, null=True, blank=True)  # GTIN/EAN
    descricao = models.CharField(max_length=255)
    categoria = models.ForeignKey(
        Categoria, null=True, blank=True, on_delete=models.PROTECT)
    marca = models.ForeignKey(
        Marca, null=True, blank=True, on_delete=models.PROTECT)
    unidade = models.ForeignKey(
        Unidade, null=True, blank=True, on_delete=models.PROTECT)
    custo = models.DecimalField(max_digits=16, decimal_places=2, validators=[
                                MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    venda = models.DecimalField(max_digits=16, decimal_places=2, validators=[
                                MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    inf_adicionais = models.CharField(max_length=255, null=True, blank=True)

    # Estoque
    estoque_minimo = models.DecimalField(max_digits=16, decimal_places=2, validators=[
                                         MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    estoque_atual = models.DecimalField(max_digits=16, decimal_places=2, validators=[
                                        MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    controlar_estoque = models.BooleanField(default=True)

    class Meta:
        verbose_name = "Produto"

    @property
    def format_unidade(self):
        if self.unidade:
            return self.unidade.sigla_unidade
        else:
            return ''

    def get_sigla_unidade(self):
        if self.unidade:
            return self.unidade.sigla_unidade
        else:
            return ''

    def get_cfop_padrao(self):
        if self.cfop_padrao:
            return self.cfop_padrao.cfop
        else:
            return ''

    def __unicode__(self):
        s = u'%s' % (self.descricao)
        return s

    def __str__(self):
        s = u'%s' % (self.descricao)
        return s

jea/apps/cadastro/forms/cliente.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import gettext_lazy as _

from jea.apps.cadastro.models.cliente import Cliente


class ClienteForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(ClienteForm, self).__init__(*args, **kwargs)
        self.fields['limite_de_credito'].localize = True

    class Meta:
        model = Cliente
        fields = ('nome_razao_social', 'tipo_pessoa', 'inscricao_municipal',
                  'limite_de_credito', 'id_estrangeiro', 'informacoes_adicionais', )
        widgets = {
            'nome_razao_social': forms.TextInput(attrs={'class': 'form-control'}),
            'tipo_pessoa': forms.RadioSelect(attrs={'class': 'form-control'}),
            'limite_de_credito': forms.TextInput(attrs={'class': 'form-control decimal-mask'}),
            'informacoes_adicionais': forms.Textarea(attrs={'class': 'form-control'}),
        }
        labels = {
            'nome_razao_social': _('Razão Social'),
            'tipo_pessoa': _(''),
            'limite_de_credito': _('Limite de Crédito'),
            'informacoes_adicionais': _('Informações Adicionais'),
        }

    def save(self, commit=True):
        instance = super(ClienteForm, self).save(commit=False)
        instance.criado_por = self.request.user
        if commit:
            instance.save()
        return 

jea/apps/estoque/forms/local.py
# -*- coding: utf-8 -*-

from django import forms
from django.utils.translation import gettext_lazy as _

from jea.apps.estoque.models.local import LocalEstoque


class LocalEstoqueForm(forms.ModelForm):

    class Meta:
        model = LocalEstoque
        fields = ('descricao',)
        widgets = {
            'descricao': forms.TextInput(attrs={'class': 'form-control'}),
        }
        labels = {
            'descricao': _('Descrição'),
        }

jea/templates/cadastro/produto/categoria_list.html
{%extends 'base/base.html'%}

{%block title%}Categoria{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid lista">
  
    <div class="title-header">
      <h2>CATEGORIAS DE PRODUTOS</h2>
    </div>
    
    {% include 'base/msg_sucesso.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lista-content">
      <div class="card">
        <form action="" method="post">
          {% csrf_token %}
          <div class="header">
            <h2>
              CATEGORIAS CADASTRADAS
            </h2>
              <div class="header-btn">
                <a href="{% url 'cadastro:addcategoriaview' %}" class="btn btn-success popup" title="Adicionar categoria"><i class="material-icons">&#xE148;</i><span> ADICIONAR</span></a>
                <button class="btn btn-red btn-remove"><i class="material-icons">&#xE872;</i></button>
              </div>
          </div>

          <div class="body">

           {% include 'base/search.html' %}

           <div class="table-responsive">
            <table id="lista-database" class="table table-bordered table-striped lista-table">
              <thead>
                <tr>
                  <th>#ID</th>                   
                  <th>Descrição</th>
                  <th>Remover</th>
                </tr>
              </thead>

              <tbody>
               {% if all_categorias%}
               {% for categoria in all_categorias %}
               <tr class="clickable-row popup" href="{% url 'cadastro:editarcategoriaview' categoria.id %}">
                <td>{{categoria.id}}</td>
                <td>{{categoria.categoria_desc}}</td>
                <td class="lista-remove">
                  <input type="checkbox" name="{{categoria.id}}" id="remover-entrada-{{categoria.id}}"/>
                  <label class="remove-entry-label" for="remover-entrada-{{categoria.id}}"></label>
                </td>
              </tr>
              {% endfor %}
              {%else%}
              {%endif%}
            </tbody>
          </table>
        </div>

      </div>

    </form>

  </div>
</div>

</div>
</section>


{%endblock%}

jea/templates/cadastro/produto/marca_list.html
{%extends 'base/base.html'%}

{%block title%}Marca{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid lista">
  
    <div class="title-header">
      <h2>MARCAS</h2>
    </div>
    
    {% include 'base/msg_sucesso.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lista-content">
      <div class="card">
        <form action="" method="post">
          {% csrf_token %}
          <div class="header">
            <h2>
              MARCAS CADASTRADAS
            </h2>
              <div class="header-btn">
                <a href="{% url 'cadastro:addmarcaview' %}" class="btn btn-success popup" title="Adicionar marca"><i class="material-icons">&#xE148;</i><span> ADICIONAR</span></a>
                <button class="btn btn-red btn-remove"><i class="material-icons">&#xE872;</i></button>
              </div>
          </div>

          <div class="body">

           {% include 'base/search.html' %}

           <div class="table-responsive">
            <table id="lista-database" class="table table-bordered table-striped lista-table">
              <thead>
                <tr>
                  <th>#ID</th>                   
                  <th>Descrição</th>
                  <th>Remover</th>
                </tr>
              </thead>

              <tbody>
               {% if all_marcas%}
               {% for marca in all_marcas %}
               <tr class="clickable-row popup" href="{% url 'cadastro:editarmarcaview' marca.id %}">
                <td>{{marca.id}}</td>
                <td>{{marca.marca_desc}}</td>
                <td class="lista-remove">
                  <input type="checkbox" name="{{marca.id}}" id="remover-entrada-{{marca.id}}"/>
                  <label class="remove-entry-label" for="remover-entrada-{{marca.id}}"></label>
                </td>
              </tr>
              {% endfor %}
              {%else%}
              {%endif%}
            </tbody>
          </table>
        </div>

      </div>

    </form>

  </div>
</div>

</div>
</section>


{%endblock%}

jea/templates/cadastro/produto/produto_tab_dados_gerais.html
<div class="col-sm-6">
    <div class="form-group">
      <div class="form-line">
        <label>{{form.codigo.label}}</label><strong style="color:red;"> *</strong>
        {% if form.codigo.errors %}<label class="error">{% for error in form.codigo.errors %}{{error}}{% endfor %}</label>{% endif %}
        {{form.codigo}}
      </div>
    </div>
  </div>
  
  <div class="col-sm-6">
    <div class="form-group">
      <div class="form-line">
        <label>{{form.descricao.label}}</label><strong style="color:red;"> *</strong>
        {% if form.descricao.errors %}<label class="error">{% for error in form.descricao.errors %}{{error}}{% endfor %}</label>{% endif %}
        {{form.descricao}}
      </div>
    </div>
  </div>
  
  <div class="col-sm-6">
    <div class="form-group">
      <div class="form-line">
        <label>{{form.codigo_barras.label}}</label>
        {% if form.codigo_barras.errors %}<label class="error">{% for error in form.codigo_barras.errors %}{{error}}{% endfor %}</label>{% endif %}
        {{form.codigo_barras}}
      </div>
    </div>
  </div>
  
  <div class="col-sm-6">
    <div class="form-group">
      <label>{{form.categoria.label}}</label>
        {% if form.categoria.errors %}<label class="error">{% for error in form.categoria.errors %}{{error}}{% endfor %}</label>{% endif %}
      <div class="input-group">
        <div class="form-line">
          {{form.categoria}}
        </div>
        <a class="input-group-addon popup" style="color: green;" title="Adicionar categoria" href="{% url 'cadastro:addcategoriaview' %}"><i class="material-icons add-new-icon" title="Adicionar">&#xE147;</i></a>
      </div>
    </div>
  </div>
  
  <div class="col-sm-6">
    <div class="form-group">
      <label>{{form.marca.label}}</label>
      {% if form.marca.errors %}<label class="error">{% for error in form.marca.errors %}{{error}}{% endfor %}</label>{% endif %}
      <div class="input-group">
        <div class="form-line">
          {{form.marca}}
        </div>
        <a class="input-group-addon popup" style="color: green;" title="Adicionar marca" href="{% url 'cadastro:addmarcaview' %}"><i class="material-icons add-new-icon" title="Adicionar">&#xE147;</i></a>
      </div>
    </div>
  </div>
  
  <div class="col-sm-6">
    <div class="form-group">
      <label>{{form.unidade.label}}</label>
      {% if form.unidade.errors %}<label class="error">{% for error in form.unidade.errors %}{{error}}{% endfor %}</label>{% endif %}
      <div class="input-group">
        <div class="form-line">
          {{form.unidade}}
        </div>
        <a class="input-group-addon popup" style="color: green;" title="Adicionar unidade" href="{% url 'cadastro:addunidadeview' %}"><i class="material-icons add-new-icon" title="Adicionar">&#xE147;</i></a>
      </div>
    </div>
  </div>
  
  <div class="col-sm-12">
    <div class="col-sm-3">
      <div class="form-group">
        <div class="form-line">
          <label>{{form.venda.label}}</label>
          {% if form.venda.errors %}<label class="error">{% for error in form.venda.errors %}{{error}}{% endfor %}</label>{% endif %}
          {{form.venda}}
        </div>
      </div>
    </div>
  
    <div class="col-sm-3">
      <div class="form-group">
        <div class="form-line">
          <label>{{form.custo.label}}</label>
          {% if form.custo.errors %}<label class="error">{% for error in form.custo.errors %}{{error}}{% endfor %}</label>{% endif %}
          {{form.custo}}
        </div>
      </div>
    </div>
  
    <div class="col-sm-3">
      <div class="form-group">
        
          <label>Margem de lucro (aprox.)</label>
          <span id="margem-lucro" style="display:block;font-size: x-large;padding-left: 10px;color: yellowgreen;">0%</span>
        
      </div>
    </div>
  </div>
  
  <div class="col-sm-6">
    <div class="form-group">
      <div class="form-line">
        <label>{{form.inf_adicionais.label}}</label>
        {% if form.inf_adicionais.errors %}<label class="error">{% for error in form.inf_adicionais.errors %}{{error}}{% endfor %}</label>{% endif %}
        {{form.inf_adicionais}}
      </div>
    </div>
  </div>

jea/templates/cadastro/produto/produto_tab_list.html
<ul class="nav nav-tabs" role="tablist">
    <li role="presentation" class="active"><a href="#tab_dados_gerais" data-toggle="tab">DADOS GERAIS</a></li>
    <li role="presentation"><a href="#tab_estoque" data-toggle="tab">ESTOQUE</a></li>
  </ul>