jea/apps/base/urls.py
from django.urls import re_path
from jea.apps.base.views import IndexView

from jea.configs.settings import DEBUG

app_name = 'base'
urlpatterns = [
    re_path(r'^$', IndexView.as_view(), name='index'),
]

jea/apps/cadastro/urls.py
from django.urls import re_path

from jea.apps.cadastro.views.empresa import AdicionarEmpresaView,EmpresasListView, EditarEmpresaView
from jea.apps.cadastro.views.cliente import AdicionarClienteView, ClientesListView,EditarClienteView
from jea.apps.cadastro.views.produto import (AdicionarProdutoView, ProdutosListView, ProdutosBaixoEstoqueListView,
                                             EditarProdutoView, AdicionarCategoriaView, CategoriasListView, EditarCategoriaView, 
                                             AdicionarUnidadeView, UnidadesListView, EditarUnidadeView,
                                             AdicionarMarcaView, MarcasListView, EditarMarcaView)
from jea.apps.cadastro.views.ajax_views import InfoCliente, InfoEmpresa, InfoProduto

app_name = 'cadastro'
urlpatterns = [
    # Empresa
    # cadastro/empresa/adicionar/
    re_path(r'empresa/adicionar/$',
        AdicionarEmpresaView.as_view(), name='addempresaview'),
    # cadastro/empresa/listaempresas
    re_path(r'empresa/listaempresas/$',
        EmpresasListView.as_view(), name='listaempresasview'),
    # cadastro/empresa/editar/
    re_path(r'empresa/editar/(?P<pk>[0-9]+)/$',
        EditarEmpresaView.as_view(), name='editarempresaview'),

    # Cliente
    # cadastro/cliente/adicionar/
    re_path(r'cliente/adicionar/$',
        AdicionarClienteView.as_view(), name='addclienteview'),
    # cadastro/cliente/listaclientes
    re_path(r'cliente/listaclientes/$',
        ClientesListView.as_view(), name='listaclientesview'),
    # cadastro/cliente/editar/
    re_path(r'cliente/editar/(?P<pk>[0-9]+)/$',
        EditarClienteView.as_view(), name='editarclienteview'),

    # Produto
    # cadastro/produto/adicionar/
    re_path(r'produto/adicionar/$',
        AdicionarProdutoView.as_view(), name='addprodutoview'),
    # cadastro/produto/listaprodutos
    re_path(r'produto/listaprodutos/$',
        ProdutosListView.as_view(), name='listaprodutosview'),
    # cadastro/produto/listaprodutos/baixoestoque
    re_path(r'produto/listaprodutos/baixoestoque/$',
        ProdutosBaixoEstoqueListView.as_view(), name='listaprodutosbaixoestoqueview'),
    # cadastro/produto/editar/
    re_path(r'produto/editar/(?P<pk>[0-9]+)/$',
        EditarProdutoView.as_view(), name='editarprodutoview'),

    # Outros
    # Categorias
    # cadastro/outros/adicionarcategoria/
    re_path(r'outros/adicionarcategoria/$',
        AdicionarCategoriaView.as_view(), name='addcategoriaview'),
    # cadastro/outros/listacategorias/
    re_path(r'outros/listacategorias/$',
        CategoriasListView.as_view(), name='listacategoriasview'),
    # cadastro/outros/editarcategoria/
    re_path(r'outros/editarcategoria/(?P<pk>[0-9]+)/$',
        EditarCategoriaView.as_view(), name='editarcategoriaview'),

    # Unidades
    # cadastro/outros/adicionarunidade/
    re_path(r'outros/adicionarunidade/$',
        AdicionarUnidadeView.as_view(), name='addunidadeview'),
    # cadastro/outros/listaunidades/
    re_path(r'outros/listaunidades/$',
        UnidadesListView.as_view(), name='listaunidadesview'),
    # cadastro/outros/editarcunidade/
    re_path(r'outros/editarunidade/(?P<pk>[0-9]+)/$',
        EditarUnidadeView.as_view(), name='editarunidadeview'),

    # Marcas
    # cadastro/outros/adicionarmarca/
    re_path(r'outros/adicionarmarca/$',
        AdicionarMarcaView.as_view(), name='addmarcaview'),
    # cadastro/outros/listamarcas/
    re_path(r'outros/listamarcas/$',
        MarcasListView.as_view(), name='listamarcasview'),
    # cadastro/outros/editarmarca/
    re_path(r'outros/editarmarca/(?P<pk>[0-9]+)/$',
        EditarMarcaView.as_view(), name='editarmarcaview'),

    # Informacoes de dada empresa (Ajax request)
    re_path(r'infoempresa/$', InfoEmpresa.as_view(), name='infoempresa'),
    re_path(r'infocliente/$', InfoCliente.as_view(), name='infocliente'),
    re_path(r'infoproduto/$', InfoProduto.as_view(), name='infoproduto'),
]

jea/apps/estoque/urls.py
# -*- coding: utf-8 -*-

from django.urls import re_path

from jea.apps.estoque.views.consulta import ConsultaEstoqueView
from jea.apps.estoque.views.local import AdicionarLocalEstoqueView,LocalEstoqueListView, EditarLocalEstoqueView
from jea.apps.estoque.views.movimento import (MovimentoEstoqueListView, AdicionarEntradaEstoqueView, EntradaEstoqueListView, DetalharEntradaEstoqueView, 
                                              AdicionarSaidaEstoqueView, SaidaEstoqueListView, AdicionarTransferenciaEstoqueView, DetalharSaidaEstoqueView,
                                              TransferenciaEstoqueListView, DetalharTransferenciaEstoqueView)


app_name = 'estoque'
urlpatterns = [
    # Consulta de estoque
    # estoque/consultaestoque/
    re_path(r'consultaestoque/$', ConsultaEstoqueView.as_view(),
        name='consultaestoqueview'),

    # Local de estoque
    # estoque/local/adicionar/
    re_path(r'local/saida/adicionar/$',
        AdicionarLocalEstoqueView.as_view(), name='addlocalview'),
    # estoque/local/listalocal
    re_path(r'local/listalocal/$', LocalEstoqueListView.as_view(),
        name='listalocalview'),
    # estoque/local/editar/
    re_path(r'local/editar/(?P<pk>[0-9]+)/$',
        EditarLocalEstoqueView.as_view(), name='editarlocalview'),

    # Movimento de estoque
    # Lista todos movimentos
    re_path(r'movimentos/$', MovimentoEstoqueListView.as_view(),
        name='listamovimentoestoqueview'),

    # EntradaEstoque
    # estoque/movimento/adicionarentrada/
    re_path(r'movimento/adicionarentrada/$',
        AdicionarEntradaEstoqueView.as_view(), name='addentradaestoqueview'),
    # estoque/movimento/listaentradas/
    re_path(r'movimento/listaentradas/$', EntradaEstoqueListView.as_view(),
        name='listaentradasestoqueview'),
    # estoque/movimento/editarentrada/
    re_path(r'movimento/editarentrada/(?P<pk>[0-9]+)/$', DetalharEntradaEstoqueView.as_view(
    ), name='detalharentradaestoqueview'),

    # SaidaEstoque
    # estoque/movimento/adicionarsaida/
    re_path(r'movimento/adicionarsaida/$',
        AdicionarSaidaEstoqueView.as_view(), name='addsaidaestoqueview'),
    # estoque/movimento/listasaidas/
    re_path(r'movimento/listasaidas/$', SaidaEstoqueListView.as_view(),
        name='listasaidasestoqueview'),
    # estoque/movimento/editarsaida/
    re_path(r'movimento/editarsaida/(?P<pk>[0-9]+)/$',
        DetalharSaidaEstoqueView.as_view(), name='detalharsaidaestoqueview'),

    # TransferenciaEstoque
    # estoque/movimento/adicionartransferencia/
    re_path(r'movimento/adicionartransferencia/$',
        AdicionarTransferenciaEstoqueView.as_view(), name='addtransferenciaestoqueview'),
    # estoque/movimento/listatransferencias/
    re_path(r'movimento/listatransferencias/$', TransferenciaEstoqueListView.as_view(),
        name='listatransferenciasestoqueview'),
    # estoque/movimento/editartransferencia/
    re_path(r'movimento/editartransferencia/(?P<pk>[0-9]+)/$', DetalharTransferenciaEstoqueView.as_view(
    ), name='detalhartransferenciaestoqueview'),
]

jea/apps/login/urls.py
from django.urls import re_path
from jea.apps.login.views import *

app_name = 'login'
urlpatterns = [
    # login/
    re_path(r'^$', UserFormView.as_view(), name='loginview'),

    # login/registrar/
    re_path(r'registrar/$', UserRegistrationFormView.as_view(),
        name='registrarview'),

    # login/esqueceu/:
    re_path(r'^esqueceu/$', ForgotPasswordView.as_view(), name='esqueceuview'),

    # login/trocarsenha/:
    re_path(r'^trocarsenha/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)$',
        PasswordResetConfirmView.as_view(), name='trocarsenhaview'),

    # logout
    re_path(r'^logout/$', UserLogoutView.as_view(), name='logoutview'),

    # login/perfil/
    re_path(r'^perfil/$', MeuPerfilView.as_view(), name='perfilview'),

    # login/editarperfil/
    re_path(r'^editarperfil/$', EditarPerfilView.as_view(), name='editarperfilview'),

    # login/usuarios/
    re_path(r'^usuarios/$', UsuariosListView.as_view(), name='usuariosview'),

    # login/usuarios/(id_usuario)
    re_path(r'usuarios/(?P<pk>[0-9]+)/$',
        UsuarioDetailView.as_view(), name='usuariodetailview'),

    # deletar usuario
    re_path(r'deletaruser/(?P<pk>[0-9]+)/$',
        DeletarUsuarioView.as_view(), name='deletarusuarioview'),

    # permissoes usuario
    re_path(r'permissoesusuario/(?P<pk>[0-9]+)/$',
        EditarPermissoesUsuarioView.as_view(), name='permissoesusuarioview'),

    # selecionar empresa
    re_path(r'selecionarempresa/$', SelecionarMinhaEmpresaView.as_view(),
        name='selecionarempresaview'),
]

jea/apps/vendas/urls.py
# -*- coding: utf-8 -*-

from django.urls import re_path

from jea.apps.vendas.views.vendas import (AdicionarPedidoVendaView, PedidoVendaListView, EditarPedidoVendaView,
                                          PedidoVendaAtrasadosListView, PedidoVendaEntregaHojeListView,
                                          GerarCopiaPedidoVendaView, GerarPDFPedidoVenda, CancelarPedidoVendaView, GerarPedidoVendaView, GerarPDFOrcamentoVenda) 
from jea.apps.vendas.views.pagamento import AdicionarCondicaoPagamentoView, CondicaoPagamentoListView, EditarCondicaoPagamentoView, InfoCondicaoPagamento
from jea.apps.vendas.views.ajax_views import InfoVenda


app_name = 'vendas'
urlpatterns = [
    # Pedidos de venda
    # vendas/pedidovenda/adicionar/
    re_path(r'pedidovenda/adicionar/$',
        AdicionarPedidoVendaView.as_view(), name='addpedidovendaview'),
    # vendas/pedidovenda/listapedidovenda
    re_path(r'pedidovenda/listapedidovenda/$',
        PedidoVendaListView.as_view(), name='listapedidovendaview'),
    # vendas/pedidovenda/editar/
    re_path(r'pedidovenda/editar/(?P<pk>[0-9]+)/$',
        EditarPedidoVendaView.as_view(), name='editarpedidovendaview'),
    # vendas/pedidovenda/listapedidovenda/atrasados
    re_path(r'pedidovenda/listapedidovenda/atrasados/$',
        PedidoVendaAtrasadosListView.as_view(), name='listapedidovendaatrasadosview'),
    # vendas/pedidovenda/listapedidovenda/hoje
    re_path(r'pedidovenda/listapedidovenda/hoje/$',
        PedidoVendaEntregaHojeListView.as_view(), name='listapedidovendahojeview'),

    # Condicao pagamento
    # vendas/pagamento/adicionar/
    re_path(r'pagamento/adicionar/$', AdicionarCondicaoPagamentoView.as_view(),
        name='addcondicaopagamentoview'),
    # vendas/pagamento/listacondicaopagamento
    re_path(r'pagamento/listacondicaopagamento/$',
        CondicaoPagamentoListView.as_view(), name='listacondicaopagamentoview'),
    # vendas/pagamento/editar/
    re_path(r'pagamento/editar/(?P<pk>[0-9]+)/$', EditarCondicaoPagamentoView.as_view(
    ), name='editarcondicaopagamentoview'),

    # Request ajax views
    re_path(r'infocondpagamento/$', InfoCondicaoPagamento.as_view(),
        name='infocondpagamento'),
    re_path(r'infovenda/$', InfoVenda.as_view(), name='infovenda'),

    # Gerar pdf pedido
    re_path(r'gerarpdfpedidovenda/(?P<pk>[0-9]+)/$',
        GerarPDFPedidoVenda.as_view(), name='gerarpdfpedidovenda'),
    # Gerar pedido a partir de um orçamento
    re_path(r'gerarpedidovenda/(?P<pk>[0-9]+)/$',
        GerarPedidoVendaView.as_view(), name='gerarpedidovenda'),
    # Copiar orcamento cancelado ou baixado
    # Copiar pedido cancelado ou baixado
    re_path(r'copiarpedidovenda/(?P<pk>[0-9]+)/$',
        GerarCopiaPedidoVendaView.as_view(), name='copiarpedidovenda'),
    # Cancelar Pedido de venda
    re_path(r'cancelarpedidovenda/(?P<pk>[0-9]+)/$',
        CancelarPedidoVendaView.as_view(), name='cancelarpedidovenda'),]

jea/urls.py
# -*- coding: utf-8 -*-

from django.urls import include, re_path
from django.contrib import admin
from django.conf.urls.static import static
from .configs.settings import DEBUG, MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^', include('jea.apps.base.urls')),
    re_path(r'^login/', include('jea.apps.login.urls')),
    re_path(r'^cadastro/', include('jea.apps.cadastro.urls')),
    re_path(r'^vendas/', include('jea.apps.vendas.urls')),
    re_path(r'^estoque/', include('jea.apps.estoque.urls')),
]

if DEBUG is True:
    urlpatterns += static(MEDIA_URL, document_root=MEDIA_ROOT)

jea/apps/base/models.py
from django.db import models

# Create your models here.

jea/apps/estoque/models/movimento.py
# -*- coding: utf-8 -*-

import operator
from django.db import models
from django.core.validators import MinValueValidator
from decimal import Decimal
from django.dispatch import receiver
from django.db.models.signals import pre_delete
from django.urls import reverse_lazy
from django.template.defaultfilters import date

from jea.apps.estoque.models.local import DEFAULT_LOCAL_ID

import locale
locale.setlocale(locale.LC_ALL, '')

TIPOS_MOVIMENTO_ENTRADA = (
    (u'0', u'Ajuste'),
    (u'1', u'Entrada por pedido de compra'),
    (u'3', u'Ajuste inicial'),
)

TIPOS_MOVIMENTO_SAIDA = (
    (u'0', u'Ajuste'),
    (u'1', u'Saída por pedido de venda'),
    (u'2', u'Saída por importação de nota fiscal'),
)


class ItensMovimento(models.Model):
    produto = models.ForeignKey('cadastro.Produto', related_name="moviment_estoque_produto",
                                on_delete=models.CASCADE, null=True, blank=True)
    movimento_id = models.ForeignKey(
        'estoque.MovimentoEstoque', related_name="itens_movimento", on_delete=models.CASCADE)
    quantidade = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                     MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    valor_unit = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                     MinValueValidator(Decimal('0.00'))], null=True, blank=True)
    subtotal = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                   MinValueValidator(Decimal('0.00'))], null=True, blank=True)

    def get_estoque_atual_produto(self):
        if self.produto:
            if self.produto.controlar_estoque and self.produto.estoque_atual:
                return self.produto.estoque_atual
            else:
                return 'Não controlado'

    def format_estoque_atual_produto(self):
        estoque_atual = self.get_estoque_atual_produto()
        if isinstance(estoque_atual, Decimal):
            return locale.format(u'%.2f', estoque_atual, 1)
        else:
            return estoque_atual


class MovimentoEstoque(models.Model):
    data_movimento = models.DateField(null=True, blank=True)
    quantidade_itens = models.IntegerField(
        validators=[MinValueValidator(0)], default=0)
    valor_total = models.DecimalField(max_digits=13, decimal_places=2, validators=[
                                      MinValueValidator(Decimal('0.00'))], default=Decimal('0.00'))
    observacoes = models.CharField(max_length=1055, null=True, blank=True)

    class Meta:
        verbose_name = "Movimento de Estoque"
        permissions = (
            ("consultar_estoque", "Pode consultar estoque"),
        )

    @property
    def format_data_movimento(self):
        return '%s' % date(self.data_movimento, "d/m/Y")

    def format_quantidade_itens(self):
        return locale.format(u'%.2f', self.quantidade_itens, 1)

    def format_valor_total(self):
        return locale.format(u'%.2f', self.valor_total, 1)


@receiver(
    pre_delete,
    sender=MovimentoEstoque,
    dispatch_uid="movimento_estoque_delete"
)
def reajusta_estoque_produtos(sender, instance, using, **kwargs):
    if hasattr(instance, "entradaestoque"):
        operation = operator.sub
    elif hasattr(instance, "saidaestoque"):
        operation = operator.add
    else:
        return
    for item in instance.itens_movimento.all():
        produto = item.produto
        produto.estoque_atual = operation(produto.estoque_atual, item.quantidade)
        produto.save()
        for produto_estocado in produto.produto_estocado.all():
            produto_estocado.quantidade = operation(produto_estocado.quantidade, item.quantidade)
            produto_estocado.save()


class EntradaEstoque(MovimentoEstoque):
    tipo_movimento = models.CharField(
        max_length=1, choices=TIPOS_MOVIMENTO_ENTRADA, default='0')
    local_dest = models.ForeignKey(
        'estoque.LocalEstoque', related_name="entrada_estoque_local", default=DEFAULT_LOCAL_ID, on_delete=models.PROTECT)

    def get_edit_url(self):
        return reverse_lazy('estoque:detalharentradaestoqueview', kwargs={'pk': self.id})

    def get_tipo(self):
        return 'Entrada'


class SaidaEstoque(MovimentoEstoque):
    tipo_movimento = models.CharField(
        max_length=1, choices=TIPOS_MOVIMENTO_SAIDA, default='0')
    pedido_venda = models.ForeignKey(
        'vendas.PedidoVenda', related_name="saida_estoque", on_delete=models.SET_NULL, null=True, blank=True)
    local_orig = models.ForeignKey(
        'estoque.LocalEstoque', related_name="saida_estoque_local", default=DEFAULT_LOCAL_ID, on_delete=models.PROTECT)

    def get_edit_url(self):
        return reverse_lazy('estoque:detalharsaidaestoqueview', kwargs={'pk': self.id})

    def get_tipo(self):
        return 'Saída'


class TransferenciaEstoque(MovimentoEstoque):
    local_estoque_orig = models.ForeignKey(
        'estoque.LocalEstoque', related_name="transf_estoque_orig", on_delete=models.CASCADE)
    local_estoque_dest = models.ForeignKey(
        'estoque.LocalEstoque', related_name="transf_estoque_dest", on_delete=models.CASCADE)

    def get_edit_url(self):
        return reverse_lazy('estoque:detalhartransferenciaestoqueview', kwargs={'pk': self.id})

    def get_tipo(self):
        return 'Transferência'

jea/templates/estoque/movimento/entradas_estoque_list_table.html
<div class="table-responsive">
    <table id="lista-database" class="table table-bordered table-striped lista-table">
      <thead>
        <tr>
          <th>#ID</th>                   
          <th>Data</th>
          <th>Tipo</th>
          <th>Fornecedor</th>
          <th>N° de itens</th>
          <th>Valor total</th>
          <th>Remover</th>
        </tr>
      </thead>
  
      <tbody>
       {% if all_entradas %}
       {% for entrada in all_entradas %}
       <tr class="clickable-row" data-href="{{entrada.get_edit_url}}">
        <td>{{entrada.id}}</td>
        <td>{{entrada.format_data_movimento}}</td>
        <td>{{entrada.get_tipo_movimento_display}}</td>
        <td>{{entrada.fornecedor|default_if_none:""}}</td>
        <td>{{entrada.format_quantidade_itens}}</td>
        <td>{{entrada.format_valor_total}}</td>
        <td class="lista-remove">
          <input type="checkbox" name="{{entrada.id}}" id="remover-movimento-{{entrada.id}}"/>
          <label class="remove-entry-label" for="remover-movimento-{{entrada.id}}"></label>
        </td>
      </tr>
      {% endfor %}
      {%else%}
      {%endif%}
    </tbody>
  </table>
  </div>

jea/templates/estoque/movimento/movimento_estoque_add.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid">

    {% include 'base/title_header.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
      <div class="row">
        <div class="card">

          <!--Header-->
          <div class="header">

            <h2>
              <a href="{{return_url}}"><i class="material-icons">&#xE5C4;</i></a>{{title_complete}}
            </h2>
            <div><small>Campos marcados com <strong style="color:red;">*</strong> são obrigatórios.</small></div>

          </div>
          <!--# Header-->

          <form role="form" action="" method="post">
            {% csrf_token %}
            
            {% include 'estoque/movimento/movimento_estoque_form.html' %}

          </form>

        </div>
      </div>
    </div>

  </div>
</section>


{%endblock%}

{% block js %}
    
  {% include 'estoque/movimento/movimento_estoque_jsblock.html' %}
  
{% endblock %}

jea/templates/estoque/movimento/movimento_estoque_jsblock.html
{% load static %}
<!-- JQuery Mask Input Js -->
<script src="{% static 'js/jquery.mask.js' %}"></script>

{% include 'base/load_jqueryui.html' %}

{% include 'base/datepicker_js.html' %}

{% include 'base/tooltip_js.html' %}

 <script type="text/javascript">
    var req_urls = {}
    req_urls.info_produto_url = "{% url 'cadastro:infoproduto' %}"
    req_urls.info_venda_url = "{% url 'vendas:infovenda' %}"
    req_urls.info_compra_url = "{% url 'compras:infocompra' %}"
    $.Admin.movimentoEstoqueForm.init(req_urls);
    $.Admin.maskInput.maskMovimentoEstoque();
    
  </script>

jea/templates/estoque/movimento/movimento_estoque_list.html
{%extends 'base/base.html'%}

{%block title%}{{title_complete|title}}{%endblock%}
{%block content%}
<section class="content">
  <div class="container-fluid lista">
  
    {% include 'base/title_header.html' %}
    
    {% include 'base/msg_sucesso.html' %}

    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 lista-content">
      <div class="card">
        <form action="" method="post">
          {% csrf_token %}
          <div class="header" style="overflow:visible;">
            <h2>
              {{title_complete}}
            </h2>
              <div class="header-btn">
                {% if add_url %}
                <a href="{{add_url}}" class="btn btn-success"><i class="material-icons">&#xE148;</i><span> ADICIONAR</span></a>
                {% else %}
                <div class="dropdown" style="display: inline-block;float:right;">
                  <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown">Adicionar
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu pull-right">
                    <li><a href="{% url 'estoque:addentradaestoqueview' %}">Entrada em estoque</a></li>
                    <li><a href="{% url 'estoque:addsaidaestoqueview' %}">Saída de estoque</a></li>
                    <li><a href="{% url 'estoque:addtransferenciaestoqueview' %}">Transferência de estoque</a></li>
                  </ul>
                </div>
                {% endif %}
                <button class="btn btn-red btn-remove"><i class="material-icons">&#xE872;</i></button>
              </div>
          </div>

          <div class="body">

           {% include 'base/search.html' %}

           {% if all_movimentos %}
           {% include 'estoque/movimento/todos_movimentos_list_table.html' %}
           {% elif all_entradas %}
           {% include 'estoque/movimento/entradas_estoque_list_table.html' %}
           {% elif all_saidas %}
           {% include 'estoque/movimento/saidas_estoque_list_table.html' %}
           {% elif all_transferencias %}
           {% include 'estoque/movimento/transferencias_estoque_list_table.html' %}
           {% else %}
           Nenhum registro encontrado
           {% endif %}

      </div>

    </form>


  </div>
</div>

</div>
</section>


{%endblock%}

{% block js %}
  {% load static %}
  <!-- JQuery Mask Input Js -->
  <script src="{% static 'js/jquery.mask.js' %}"></script>
  
  {% include 'base/load_jqueryui.html' %}

  {% include 'base/datepicker_js.html' %}

  {% include 'base/tooltip_js.html' %}

  <script type="text/javascript">
    var req_urls = {}

    $.Admin.maskInput.maskLancamento();
    $.Admin.lancamentoList.init(req_urls);
  </script>
  
{% endblock %}

jea/templates/estoque/movimento/saidas_estoque_list_table.html
<div class="table-responsive">
    <table id="lista-database" class="table table-bordered table-striped lista-table">
      <thead>
        <tr>
          <th>#ID</th>                   
          <th>Data</th>
          <th>Tipo</th>
          <th>N° de itens</th>
          <th>Valor total</th>
          <th>Remover</th>
        </tr>
      </thead>
  
      <tbody>
       {% if all_saidas %}
       {% for saida in all_saidas %}
       <tr class="clickable-row" data-href="{{saida.get_edit_url}}">
        <td>{{saida.id}}</td>
        <td>{{saida.format_data_movimento}}</td>
        <td>{{saida.get_tipo_movimento_display}}</td>
        <td>{{saida.format_quantidade_itens}}</td>
        <td>{{saida.format_valor_total}}</td>
        <td class="lista-remove">
          <input type="checkbox" name="{{saida.id}}" id="remover-movimento-{{saida.id}}"/>
          <label class="remove-entry-label" for="remover-movimento-{{saida.id}}"></label>
        </td>
      </tr>
      {% endfor %}
      {%else%}
      {%endif%}
    </tbody>
  </table>
  </div>

jea/templates/estoque/movimento/todos_movimentos_list_table.html
<div class="table-responsive">
    <table id="lista-database" class="table table-bordered table-striped lista-table">
      <thead>
        <tr>
          <th>#ID</th>                   
          <th>Data</th>
          <th>Tipo</th>
          <th>N° de itens</th>
          <th>Valor total</th>
          <th>Remover</th>
        </tr>
      </thead>
  
      <tbody>
       {% if all_movimentos %}
       {% for movimento in all_movimentos %}
       <tr class="clickable-row" data-href="{{movimento.get_edit_url}}">
        <td>{{movimento.id}}</td>
        <td>{{movimento.format_data_movimento}}</td>
        <td>{{movimento.get_tipo}}</td>
        <td>{{movimento.format_quantidade_itens}}</td>
        <td>{{movimento.format_valor_total}}</td>
        <td class="lista-remove">
          <input type="checkbox" name="{{movimento.id}}" id="remover-movimento-{{movimento.id}}"/>
          <label class="remove-entry-label" for="remover-movimento-{{movimento.id}}"></label>
        </td>
      </tr>
      {% endfor %}
      {%else%}
      {%endif%}
    </tbody>
  </table>
  </div>